### PR TITLE
Prefix StackOtter fork for conflicting lib names.

### PR DESCRIPTION
**Pull request by furby-tm**
### Intro

**Swift Bundler** [made this change](https://github.com/stackotter/swift-bundler/blob/05bef3265beef8124879d62bf7b3a18e41906488/Package.swift#L12) while adding support for **visionOS**. 

## Proposed Solution
- [x] Remove dependency mangling which is otherwise a _warning_ in **Swift 5.9** and an _error_ in **Swift 6.0**.
- [x] Update with the latest [`v1.2.3` release](https://github.com/apple/swift-argument-parser/releases/tag/1.2.3) from apple

## Outlined Changes

The following _"fix"_ issued for this package:

* Changed all instances of `ArgumentParser` to `StackOtterArgParser`.
  * To eliminate dependency mangling with Apple's same-name package targets for `swift-argument-parser`.

##### NOTE: Aliasing would be a cleaner solution, but is not possible under the **minimum 5.6 build tools**.

<br/>

#### Reference Documentation
[[SWIFT-0292] Package Registry Service Proposal - Package Name Collision Resolution](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md#package-name-collision-resolution)

### CODE REVIEW

**Comment by stackotter** [comment]
I think you've accidentally formatted all of the files that you've touched (from 4 space tabs to 2 space tabs) which means that there are 12000 additions 😅 Could you please try reformatting to reduce the number of changes that I have to look at?

> Aliasing would be a cleaner solution, but is not possible under the minimum 5.6 build tools.

Yeah that's so unfortunate. I wish Swift wasn't so infuriatingly tied into the platform version on Apple devices. I want to support back to macOS Catalina for the time being, so 5.6 it is.

> * Update with the latest [`v1.2.3` release](https://github.com/apple/swift-argument-parser/releases/tag/1.2.3) from apple

Thanks for that too, that'll probably be handy at some point.

**Comment by furby-tm** [comment]
> I think you've accidentally formatted all of the files that you've touched (from 4 space tabs to 2 space tabs) which means that there are 12000 additions 😅 Could you please try reformatting to reduce the number of changes that I have to look at?

Oh gosh lol. I don't know how I missed that, I have swiftformat installed and it makes it far too easy to accidentally do mass reformats, and mine is even worse because it's configured on the save hotkey / vscode just does it when I type

**Comment by furby-tm** [comment]
> Yeah that's so unfortunate. I wish Swift wasn't so infuriatingly tied into the platform version on Apple devices. I want to support back to macOS Catalina for the time being, so 5.6 it is.

I feel like most of us just go in there and start preprocessing things out per platform, myself included, and all that does in this scenario is obliterate every last library in existence from being able to work with some new platform from the outset.

At the very least there should be a swift command at build time, in the form of flags, which one can conditionally turn all specific conditions `# os(iOS)` on as an overridden constant.

That's the flexibility you get with C/C++ when it comes to CMAKE.

I have not jumped into too much of the new macro stuff for Swift 5.9 but is there perhaps a way to extend a macro? Such as `# os()`?

I guess I don't mean "extension" in the typical context, it'd probably end up being something closer to SwiftSyntax but yeah it's going to take a long long while before third party maintainers will get around to doing that.

Unfortunately it causes us to sit upon an ocean of forked Swift dependencies, my org for example is just chock-full of them, unfortunately I don't really know a better alternative.

**Comment by stackotter** [comment]
> I feel like most of us just go in there and start preprocessing things out per platform

Yeah, that works until you want to use a new feature (such as macros) to clean up a codebase. In rust you would just update your rust version, but in swift if you bump your tools version, then suddenly people on older OSes can’t work on your project anymore (which wouldn’t matter to a company making iOS apps, but it does to open source devs wanting contributions)

The new macros dont allow you to modify existing builtin macros, but they do allows you to basically implement anything (including platform checking or whatever). Unfortunately they wouldn’t help for supporting people on older Swift versions because they require 5.9

**Comment by furby-tm** [comment]
Curious, is there a Swift plugin for doing a git patch file on a dependency? That might actually help substantially with these sorts of things

**Comment by stackotter** [comment]
> Curious, is there a Swift plugin for doing a git patch file on a dependency? That might actually help substantially with these sorts of things

That would be cool, but doesn’t exist that I know of. It may be pretty tricky to implement because plugins are sandboxed to certain directories.

**Comment by furby-tm** [comment]
Going to try and get this cleaned up for you, this time with `swiftformat` disabled 😆. Also the prospect of your delta-client Minecraft possibly being made available on visionOS is exciting! Am curious if you've been able to get any deeper into what sort of Metal APIs are available for that yet, probably too early to do anything "HoloLens Exciting", but that doesn't seem too far off at this point.

**Comment by furby-tm** [comment]
Closing this PR in favor of the fresh PR [here](https://github.com/stackotter/swift-argument-parser/pull/2/commits/d490f73b34565c43114420aaef3364057a8e7ece).

**Pull request closed without merging**
